server:
    port: 8090
spring:
    application:
        name : gateway
    cloud:
        gateway:
            routes:
            -   id : doctorModule
                uri : lb://doctor-service
                predicates:
                - Path=/doctors/**
            -   id : patientModule
                uri : lb://patient-service
                predicates:
                - Path= /patients/**
            -   id : appointmentModule
                uri : lb://appointment-service
                predicates:
                - Path=/appointments/**
               
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka
    
