server:
    port: 8080
spring:
    application:
        name: doctor-service
    datasource:
        url: jdbc:mysql://localhost:3306/doctors_db
        username: root
        password:



eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka
    
