server:
    port: 8081
spring:
    application:
        name: patient-service
    datasource:
        url: jdbc:mysql://localhost:3306/patients_db
        username: root
        password:



eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka
      
